### ISSUE TITLE
定时任务的属性和状态我只想通过application.properties配置，为什么要从数据库读取，增加IO开销？

### ISSUE THREAD

**Issue by wujunshen** [icnws/spring-data-jpa-demo#2]
我个人觉得所有定时任务的属性和状态从数据库读取属于架构设计的过度设计。或是为了支持你本身JPA的repository

**Comment by icnws** [comment]
之所以要这样做是定时任务框架那十几个表很不喜欢，所以自己设计了一个简单实现，至于是否适合你的场景需要，你可以自己进行评估
